### ISSUE TITLE
[BUG] Assertion Error in generate_tokens_probs_and_return_on_first_stage when pp > 1

### ISSUE THREAD

**Issue by loofahcus** [alibaba/ChatLearn#131]
**Describe the bug**
Assertion Failed for assert tensor.is_contiguous():

```
(PolicyInference pid=226487, ip=10.236.245.246) ERROR:ChatLearn-policy:Catch exception ========= in policy forward_step  [repeated 3x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246) Traceback (most recent call last): [repeated 75x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)   File "/gpfs/lichao/Codes/ChatLearn/chatlearn/runtime/decorator.py", line 166, in inner [repeated 225x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)     return func(self, *args, **kwargs) [repeated 75x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)     ret = func(self, *args, **kwargs) [repeated 150x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)   File "/gpfs/lichao/Codes/ChatLearn/examples/megatron/models/old_policy_inference.py", line 408, in forward_step [repeated 75x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)     return self._forward_step(data, iteration, eval_mode=False) [repeated 75x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)   File "/usr/local/lib/python3.10/dist-packages/ray/util/tracing/tracing_helper.py", line 467, in _resume_span [repeated 150x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)     return method(self, *_args, **_kwargs) [repeated 150x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)   File "/gpfs/lichao/Codes/ChatLearn/examples/megatron/models/old_policy_inference.py", line 362, in _forward_step [repeated 75x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)     tokens, all_log_probs = self.generate( [repeated 75x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)   File "/gpfs/lichao/Codes/ChatLearn/examples/megatron/models/old_policy_inference.py", line 290, in generate [repeated 75x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)     res = generate_tokens_probs_and_return_on_first_stage( [repeated 75x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)   File "<string>", line 205, in generate_tokens_probs_and_return_on_first_stage [repeated 75x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)   File "/gpfs/lichao/Codes/Megatron-LM.nv/megatron/inference/text_generation/communication.py", line 95, in broadcast_from_last_to_first_pipeline_stage [repeated 75x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)     _is_cuda_contiguous(tensor) [repeated 75x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)   File "/gpfs/lichao/Codes/Megatron-LM.nv/megatron/inference/text_generation/communication.py", line 55, in _is_cuda_contiguous [repeated 75x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246)     assert tensor.is_contiguous() [repeated 75x across cluster]
(PolicyInference pid=226487, ip=10.236.245.246) AssertionError [repeated 75x across cluster]
```

**To Reproduce**
Run with RLHF setting with model pipeline_parallel > 1

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/f75117f2-1c7d-4386-8084-999de18e4845)

**Additional context**

**Comment by SeaOfOcean** [comment]
This is a megatron bug in text generation when pipeline is enabled, see https://github.com/NVIDIA/Megatron-LM/pull/570

**Comment by haolin-nju** [comment]
Closed. We have merged a related FAQ. Please refer to PR #132 .
