### ISSUE TITLE
[BUG] import error for importlib.util and unable to use Megatron-LM

### ISSUE THREAD

**Issue by Chlience** [alibaba/ChatLearn#148]
Sysinfo
```
python=3.9
```

import error when use `scripts/convert_hf_to_megatron.sh`
```
export MEGATRON=/app/Megatron-LM
export CHATLEARN=/app/ChatLearn

cd ${CHATLEARN}/examples/megatron/

TP=4 \
PP=1 \
LOAD_PATH=/app/Llama-2-7b-hf \
TOKENIZER_MODEL=$LOAD_PATH/tokenizer.model \
SAVE_PATH=/app/Llama-2-7b-hf-megatron \
bash scripts/convert_hf_to_megatron.sh
```

I get error info below:
```
+ model=gpt_llama
+ use_legacy_models=True
+ tp=4
+ pp=1
+ ep=1
+ megatron=/app/Megatron-LM
+ chatlearn=/app/ChatLearn
+ export PYTHONPATH=/app/Megatron-LM:/app/ChatLearn
+ PYTHONPATH=/app/Megatron-LM:/app/ChatLearn
+ load_dir=/app/Llama-2-7b-hf
+ save_dir=/app/Llama-2-7b-hf-megatron
+ tokenizer_model=/app/Llama-2-7b-hf/tokenizer.model
+ model_size=llama2-7B
+ export CUDA_DEVICE_MAX_CONNECTIONS=1
+ CUDA_DEVICE_MAX_CONNECTIONS=1
+ set +x
Traceback (most recent call last):
  File "/app/ChatLearn/chatlearn/tools/megatron_checkpoint_utils.py", line 265, in <module>
    if exist_checkpoint_util():
  File "/app/ChatLearn/chatlearn/tools/megatron_checkpoint_utils.py", line 167, in exist_checkpoint_util
    spec = importlib.util.find_spec('tools.checkpoint.util')
AttributeError: module 'importlib' has no attribute 'util'
Conversion is done, using time: 0 min 0 sec
```

After I added `import  importlib.util` to fix it, I got Megatron-LM import error:
```
+ model=gpt_llama
+ use_legacy_models=True
+ tp=4
+ pp=1
+ ep=1
+ megatron=/app/Megatron-LM
+ chatlearn=/app/ChatLearn
+ export PYTHONPATH=/app/Megatron-LM:/app/ChatLearn
+ PYTHONPATH=/app/Megatron-LM:/app/ChatLearn
+ load_dir=/app/Llama-2-7b-hf
+ save_dir=/app/Llama-2-7b-hf-megatron
+ tokenizer_model=/app/Llama-2-7b-hf/tokenizer.model
+ model_size=llama2-7B
+ export CUDA_DEVICE_MAX_CONNECTIONS=1
+ CUDA_DEVICE_MAX_CONNECTIONS=1
+ set +x
Loaded loader_llama_mistral as the loader.
Loaded saver_megatron as the saver.
Starting saver...
Starting loader...
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Unable to import Megatron, please specify the path to Megatron using --megatron-path. Exiting.
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Unable to import Megatron, please specify the path to Megatron using --megatron-path. Exiting.
Conversion is done, using time: 0 min 4 sec
```

How can I fix it?

**Comment by haolin-nju** [comment]
Hi. What's your Megatron commit id? The script was tested on Megatron-LM [core_r0.8.0](https://github.com/NVIDIA/Megatron-LM/releases/tag/core_r0.8.0). Please refer to https://github.com/alibaba/ChatLearn/blob/main/docs/en/installation.md for aligning the environment setup with us. If you need further assistance, feel free to contact us. :)

**Comment by Chlience** [comment]
commit 5161b168956a98a7cb95a3d013f8fa0822fb0595
It's same as guide.

**Comment by Chlience** [comment]
My commit id is 5161b1689, same as https://chatlearn.readthedocs.io/en/stable/installation.html but not Megatron-LM core_r0.8.0.
Everything is OK now after changing it.

**Comment by haolin-nju** [comment]
> My commit id is 5161b1689, same as https://chatlearn.readthedocs.io/en/stable/installation.html but not Megatron-LM core_r0.8.0. Everything is OK now after changing it.

Glad to hear that! We will fix the doc.  cc@SeaOfOcean
