### ISSUE TITLE
[BUG] Could Not use APEX and TransformerEngine when use convert_hf_to_megatron

### ISSUE THREAD

**Issue by Chlience** [alibaba/ChatLearn#155]
Sysinfo
```
nvidia/cuda:12.2.2-cudnn8-devel-ubuntu22.04
python=3.10.12
megatron-lm=core_r0.8.0
transformer-engine=v1.2.1
apex=e552ad997605dd883825106776eba230a6820345(newest)
```

Error message 
```
Traceback (most recent call last):
  File "/app/ChatLearn/chatlearn/tools/megatron_checkpoint_utils.py", line 284, in <module>
    convert.main()
  File "/app/Megatron-LM/tools/checkpoint/convert.py", line 147, in main
    loader.load_checkpoint(queue, args)
Loader exited, exiting saver
  File "/app/Megatron-LM/tools/checkpoint/loader_llama_mistral.py", line 664, in load_checkpoint
    _load_checkpoint(queue, args)
  File "/app/Megatron-LM/tools/checkpoint/loader_llama_mistral.py", line 571, in _load_checkpoint
    model = load_checkpoint_to_model(margs)
  File "/app/Megatron-LM/tools/checkpoint/loader_llama_mistral.py", line 409, in load_checkpoint_to_model
    model = model_provider(True, True).to(args.params_dtype)
  File "/app/Megatron-LM/pretrain_gpt.py", line 62, in model_provider
    model = megatron.legacy.model.GPTModel(
  File "/app/Megatron-LM/megatron/legacy/model/gpt_model.py", line 61, in __init__
    self.language_model, self._language_model_key = get_language_model(
  File "/app/Megatron-LM/megatron/legacy/model/language_model.py", line 68, in get_language_model
    language_model = TransformerLanguageModel(
  File "/app/Megatron-LM/megatron/legacy/model/language_model.py", line 388, in __init__
    self.encoder = ParallelTransformer(
  File "/app/Megatron-LM/megatron/legacy/model/transformer.py", line 1584, in __init__
    [build_layer(i + 1 + offset) for i in range(self.num_layers)])
  File "/app/Megatron-LM/megatron/legacy/model/transformer.py", line 1584, in <listcomp>
    [build_layer(i + 1 + offset) for i in range(self.num_layers)])
  File "/app/Megatron-LM/megatron/legacy/model/transformer.py", line 1489, in build_layer
    return ParallelTransformerLayer(
  File "/app/Megatron-LM/megatron/legacy/model/transformer.py", line 879, in __init__
    self.self_attention = ParallelAttention(
  File "/app/Megatron-LM/megatron/legacy/model/transformer.py", line 556, in __init__
    self.query_key_value = tensor_parallel.ColumnParallelLinear(
  File "/app/Megatron-LM/megatron/core/tensor_parallel/layers.py", line 810, in __init__
    raise RuntimeError(
RuntimeError: ColumnParallelLinear was called with gradient_accumulation_fusion set to True but the custom CUDA extension fused_weight_gradient_mlp_cuda module is not found. To use gradient_accumulation_fusion you must install APEX with --cpp_ext and --cuda_ext. For example: pip install --global-option="--cpp_ext" --global-option="--cuda_ext ." Note that the extension requires CUDA>=11. Otherwise, you must turn off gradient accumulation fusion.
```

This seems to be an issue with Megatron-LM, but I wonder if the apex and transformer-engine versions are as expected. Any help would be appreciated.

**Comment by SeaOfOcean** [comment]
You may try the pre-built image registry.cn-wulanchabu.aliyuncs.com/pai-dlc/pytorch-training:2.4.0-gpu-py3.10-cu12.5-ngc24.06-ubuntu22.04

**Comment by adoda** [comment]
Any question you can reopen the issue.
