### ISSUE TITLE
[BUG] `mp_rank_00_000` could be optim and dense model doesn't have ep size in vllm_utils.py

### ISSUE THREAD

**Issue by haolin-nju** [alibaba/ChatLearn#176]
**Describe the bug**
For QWen dense model:
1. https://github.com/alibaba/ChatLearn/blob/39a97077ee9978331806e02cc0283fdcbbc2aef0/chatlearn/utils/vllm_utils.py#L754 `mp_rank_00_000` could be optim. 

2. https://github.com/alibaba/ChatLearn/blob/39a97077ee9978331806e02cc0283fdcbbc2aef0/chatlearn/utils/vllm_utils.py#L1163 dense model doesn't have ep size.

**Additional context**
1. 
```bash
 Traceback (most recent call last):
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/runtime/decorator.py", line 34, in inner
     return func(self, *args, **kwargs)
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/runtime/decorator.py", line 63, in inner
     ret = func(self, *args, **kwargs)
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/models/vllm_module.py", line 544, in model_setup
     super().model_setup()
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/models/torch_module.py", line 43, in model_setup
     super().model_setup()
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/models/base_module.py", line 261, in model_setup
     self.setup()
   File "/usr/local/lib/python3.10/dist-packages/ray/util/tracing/tracing_helper.py", line 467, in _resume_span
     return method(self, *_args, **_kwargs)
   File "/tmp/ray/session_2024-12-13_06-49-10_242629_184/runtime_resources/working_dir_files/_ray_pkg_e077a68e203ad218/vllm_policy_inference.py", line 65, in setup
     model = [get_model(self.model_provider, self.model_args, need_load_ckpt)]
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/utils/vllm_utils.py", line 552, in get_model
     model.load_weights()
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/models/vllm/vllm_model.py", line 68, in load_weights
     load_checkpoint(self, None, None)
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/utils/vllm_utils.py", line 1503, in load_checkpoint
     return vllm_load_checkpoint(model, optimizer, opt_param_scheduler, load_arg=load_arg, strict=strict)
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/utils/vllm_utils.py", line 1562, in vllm_load_checkpoint
     model[0].load_state_dict(state_dict['model'], strict=strict)
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/models/vllm/vllm_model.py", line 89, in load_state_dict
     state_dict = convert_state_dict_internal(self.model_args, self.config.hf_config, qwen_version=qwen_version)
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/utils/vllm_utils.py", line 1133, in convert_qwen_state_dict_from_megatron_to_vllm
     state_dict = load_state_dict(args)
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/utils/vllm_utils.py", line 750, in load_state_dict
     rank0_checkpoint_path = rank0_checkpoint_name[0]
 IndexError: list index out of range
```
2.
```bash
 [2024-12-13 06:59:02,775 ChatLearn-policy 200.7.239.242 RANK:0] (decorator.py 45): ERROR 
 Traceback (most recent call last):
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/runtime/decorator.py", line 34, in inner
     return func(self, *args, **kwargs)
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/runtime/decorator.py", line 63, in inner
     ret = func(self, *args, **kwargs)
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/models/vllm_module.py", line 544, in model_setup
     super().model_setup()
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/models/torch_module.py", line 43, in model_setup
     super().model_setup()
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/models/base_module.py", line 261, in model_setup
     self.setup()
   File "/usr/local/lib/python3.10/dist-packages/ray/util/tracing/tracing_helper.py", line 467, in _resume_span
     return method(self, *_args, **_kwargs)
   File "/tmp/ray/session_2024-12-13_06-57-51_053533_184/runtime_resources/working_dir_files/_ray_pkg_e077a68e203ad218/vllm_policy_inference.py", line 65, in setup
     model = [get_model(self.model_provider, self.model_args, need_load_ckpt)]
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/utils/vllm_utils.py", line 552, in get_model
     model.load_weights()
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/models/vllm/vllm_model.py", line 68, in load_weights
     load_checkpoint(self, None, None)
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/utils/vllm_utils.py", line 1507, in load_checkpoint
     return vllm_load_checkpoint(model, optimizer, opt_param_scheduler, load_arg=load_arg, strict=strict)
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/utils/vllm_utils.py", line 1566, in vllm_load_checkpoint
     model[0].load_state_dict(state_dict['model'], strict=strict)
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/models/vllm/vllm_model.py", line 89, in load_state_dict
     state_dict = convert_state_dict_internal(self.model_args, self.config.hf_config, qwen_version=qwen_version)
   File "/anonymous/2024-11-27/ChatLearn/chatlearn/utils/vllm_utils.py", line 1154, in convert_qwen_state_dict_from_megatron_to_vllm
     ep_size = megatron_args.moe_expert_model_parallel_size
 AttributeError: 'Namespace' object has no attribute 'moe_expert_model_parallel_size'
```

**Comment by haolin-nju** [comment]
Done in PR #178 .
